using Microsoft.EntityFrameworkCore;
using MoiBackend.Core.Interfaces;
using MoiBackend.Infrastructure.Data;
using MoiBackend.Infrastructure.Services;

var builder = WebApplication.CreateBuilder(args);

// Force listening on port 8080
builder.WebHost.UseUrls("http://localhost:8080");

builder.Services.AddControllers();

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? "Host=localhost;Port=5432;Database=moi_db;Username=postgres;Password=postgres";

builder.Services.AddDbContext<MoiDbContext>(options =>
    options.UseNpgsql(connectionString));

// Register Application Services
builder.Services.AddScoped<IMoiService, MoiService>();
builder.Services.AddScoped<IGoldEntryService, GoldEntryService>();
builder.Services.AddScoped<IReportService, ReportService>();
builder.Services.AddScoped<IGivenMoiService, GivenMoiService>();
builder.Services.AddScoped<IConflictService, ConflictService>();
builder.Services.AddScoped<IPendingReturnService, PendingReturnService>();

builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyHeader()
              .AllowAnyMethod();
    });
});

var app = builder.Build();

// Auto-migrate Database tables on startup
using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<MoiDbContext>();
    try
    {
        await dbContext.Database.EnsureCreatedAsync();

        // Existing columns migrations
        await dbContext.Database.ExecuteSqlRawAsync("ALTER TABLE events ADD COLUMN IF NOT EXISTS invitation_image text;");
        await dbContext.Database.ExecuteSqlRawAsync("ALTER TABLE moi_transactions ADD COLUMN IF NOT EXISTS gift_term text;");
        await dbContext.Database.ExecuteSqlRawAsync("ALTER TABLE moi_transactions ADD COLUMN IF NOT EXISTS return_amount numeric(19,2);");
        await dbContext.Database.ExecuteSqlRawAsync("ALTER TABLE moi_transactions ADD COLUMN IF NOT EXISTS notes text;");

        // Given Moi table and new columns
        await dbContext.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS given_moi_entries (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                recipient_name text NOT NULL,
                village text,
                amount numeric(19,2) NOT NULL,
                gift_type text DEFAULT 'Cash',
                gold_details text,
                occasion text,
                gift_term text,
                given_date timestamp with time zone NOT NULL,
                notes text,
                event_id bigint REFERENCES events(id) ON DELETE SET NULL
            );
        ");
        await dbContext.Database.ExecuteSqlRawAsync("ALTER TABLE given_moi_entries ADD COLUMN IF NOT EXISTS gift_type text DEFAULT 'Cash';");
        await dbContext.Database.ExecuteSqlRawAsync("ALTER TABLE given_moi_entries ADD COLUMN IF NOT EXISTS gold_details text;");

        // Conflict Records table (NEW)
        await dbContext.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS conflict_records (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                recipient_name text NOT NULL,
                village text,
                our_given_amount numeric(19,2) NOT NULL,
                their_total_gift_amount numeric(19,2) NOT NULL DEFAULT 0,
                conflict_status text NOT NULL DEFAULT 'NoPreviousRecord',
                conflict_note text,
                given_moi_entry_id bigint,
                event_id bigint REFERENCES events(id) ON DELETE SET NULL,
                checked_at timestamp with time zone NOT NULL DEFAULT NOW()
            );
        ");

        // Pending Returns table (NEW)
        await dbContext.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS pending_returns (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                contributor_name text NOT NULL,
                village text,
                received_amount numeric(19,2) NOT NULL DEFAULT 0,
                occasion text,
                status text NOT NULL DEFAULT 'Pending',
                created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                closed_at timestamp with time zone,
                notes text,
                moi_transaction_id bigint,
                given_moi_entry_id bigint,
                event_id bigint REFERENCES events(id) ON DELETE SET NULL
            );
        ");

        // Users table (NEW - Real Database Auth)
        await dbContext.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS users (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username text NOT NULL UNIQUE,
                password_hash text NOT NULL,
                full_name text,
                role text DEFAULT 'user',
                privileges_json text,
                is_active boolean DEFAULT true,
                created_at timestamp with time zone DEFAULT NOW()
            );
        ");

        // Auto-seed default Admin account if no users exist
        await dbContext.Database.ExecuteSqlRawAsync(@"
            INSERT INTO users (username, password_hash, full_name, role, privileges_json, is_active)
            SELECT 'Admin', 'Admin@123', 'System Administrator', 'admin', '', true
            WHERE NOT EXISTS (SELECT 1 FROM users WHERE LOWER(username) = 'admin');
        ");
    }
    catch (Exception ex)
    {
        app.Logger.LogError(ex, "An error occurred while creating/migrating the PostgreSQL database.");
    }
}

app.UseCors("AllowAll");
app.UseAuthorization();
app.MapControllers();

app.Run();
